---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy custom Nginx default configuration
  copy:
    src: default.conf
    dest: /etc/nginx/sites-enabled/default

- name: Start Nginx and enable it at boot
  systemd:
    name: nginx
    state: started
    enabled: yes
  notify: Reload Nginx

- name: Include Exporter Tasks
  include_tasks: exporters/main.yaml


