---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Start Nginx and enable it at boot
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy custom Nginx default configuration
  copy:
    src: roles/nginx/files/default/uwsgi_frontend.conf
    dest: /etc/nginx/sites-enabled/default
  notify: Reload nginx
  become: yes
