---
  - name: Installation HAProxy
    apt:
      name: haproxy
  
  - name: HAProxy Configuration
    template:
      src: haproxy.conf.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: Restart HAProxy

  - name: Ensure HAProxy is enabled  
    service: 
      name: haproxy
      state: started
      enabled: yes 

########EXPORTES#########

  - name: HAProxy exporters
    apt:
      name: prometheus-haproxy-exporter
      state: present
  
  - name: Configure prometheus-haproxy-exporter
    lineinfile:
      path: /etc/default/prometheus-haproxy-exporter
      line: 'ARGS="--haproxy.scrape-uri=http://localhost:{{ haproxy_port }}/haproxy/stats;csv"'
    notify: Restart prometheus-haproxy-exporter
  
  - name: Ensure HAProxy exporter is enabled
    service: 
      name: prometheus-haproxy-exporter
      state: started
      enabled: yes 


  


    

