- name: Create Grafana directory
  file:
    name: /opt/grafana
    state: directory

- name: Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: Restart Grafana Container

- name: Install Grafana in Docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: 
      - /opt/grafana:/etc/grafana

- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/opt/grafana/provisioning/dashboards"
    - "/opt/grafana/provisioning/datasources"
  
- name: Copy Prometheus data source configuration
  copy:
    src: datasource.yaml  
    dest: /opt/grafana/provisioning/datasources/prometheus.yaml

- name: Copy json configuration
  copy:
    src: dashboard-source.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboard-source.yaml
  
- name: Copy main.json to Docker host
  copy:
    src: main.json
    dest: /opt/grafana/provisioning/dashboards

- name: Copy syslog json dashboard
  copy:
    src: syslog.json
    dest: /opt/grafana/provisioning/dashboards

- name: Copy MySQL json dashboard
  copy:
    src: mysql.json
    dest: /opt/grafana/provisioning/dashboards

- name: Create Grafana provisioning files
  file:
    path: "{{ item }}"
    state: touch
  loop:
    - "/opt/grafana/grafana.ini"
    - "/opt/grafana/provisioning/dashboards/dashboard-source.yaml"
    - "/opt/grafana/provisioning/datasources/datasource.yaml"
    - "/opt/grafana/provisioning/dashboards/main.json"
    - "/opt/grafana/provisioning/dashboards/mysql.json"
    - "/opt/grafana/provisioning/dashboards/syslog.json"
  notify: Restart Grafana Container

