- name: Import Grafana APT GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana OSS
  apt:
    name: grafana
    state: present

- name: Update package repositories and upgrade packages
  apt:
    update_cache: yes

- name: Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini 
  notify: Restart grafana

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
