- name: Create Grafana directory
  file:
    name: /opt/grafana
    state: directory

- name: Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: Restart Grafana Container

- name: Install Grafana in Docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: 
      - /opt/grafana:/etc/grafana

- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/opt/grafana/provisioning/dashboards"
    - "/opt/grafana/provisioning/datasources"
  
- name: Copy dashboard configurations
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'dashboard-source.yaml', dest: '/opt/grafana/provisioning/dashboards/dashboard-source.yaml'}
    - { src: 'datasource.yaml', dest: '/opt/grafana/provisioning/datasources/datasource.yaml'}
    - { src: 'main.json', dest: '/opt/grafana/provisioning/dashboards/main.json' }
    - { src: 'syslog.json', dest: '/opt/grafana/provisioning/dashboards/syslog.json' }
    - { src: 'mysql.json', dest: '/opt/grafana/provisioning/dashboards/mysql.json' }
    - { src: 'haproxy_keepalived.json', dest: '/opt/grafana/provisioning/dashboards/haproxy_keepalived.json' }
  notify: Restart Grafana Container



