- name: Install uWSGI Packages
  apt:
    name: uwsgi
    state: present
  become: yes

- name: Install uWSGI Package
  apt:
    name: uwsgi-plugin-python3
    state: present
  become: yes

# - name: Ensure /etc/uwsgi/apps-enabled/agama.ini is owned by agama
#   file:
#     path: /etc/uwsgi/apps-enabled/agama.ini
#     owner: agama
#     group: agama
#     state: directory
#   become: yes

- name: Copy uWSGI config for AGAMA application
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    group: agama
  notify: Restart uWSGI
  become: yes

- name: Ensure uWSGI service is running
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
  become: yes
