- name: Restart bind9
  service:
    name: bind9
    state: restarted
  become: yes

- name: Restart prometheus-bind-exporter
  service:
    name: prometheus-bind-exporter
    state: restarted

- name: Reload Zone 
  command: rndc reload
