- name: Create/ensure user agama
  user:
    name: agama
    state: present

- name: Ensure /opt/agama Directory 
  file:
    path: /opt/agama
    owner: agama
    group: agama
    state: directory
  become: yes

- name: Install AGAMA Dependencies using APT
  apt:
    name: python3-flask-sqlalchemy
    state: present
  become: yes

- name: Download AGAMA Application 
  get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py"
    dest: "/opt/agama/agama.py"
  become: yes





