- name: Install MySQL Exporter from Ubuntu Repository
  apt:
    name: prometheus-mysqld-exporter
    state: present
  tags:
    - mysqlex

- name: Create MySQL 'exporter' User
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  no_log: true

- name: Create ~/.my.cnf for Exporter User
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  no_log: true

- name: Update Prometheus MySQL Exporter for Replication Metrics
  lineinfile:
    path: /etc/default/prometheus-mysqld-exporter
    line: 'ARGS="--collect.slave_status"'
  notify:
    - Restart Prometheus MySQL Exporter

- name: Ensure Exporter Restarts 
  systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
