- name: Install MySQL Exporter from Ubuntu Repository
  apt:
    name: prometheus-mysqld-exporter
    state: present
  tags:
    - mysqlex

- name: Create MySQL 'exporter' User
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create ~/.my.cnf for Exporter User
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf

- name: Ensure Exporter Restarts 
  systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes