  - name: Install MySQL Server package
    apt:
      name: mysql-server
      state: present
    become: yes

  - name: Ensure MySQL service is started and enabled
    service:
      name: mysql
      state: started
      enabled: yes
    notify: Reload Mysql
  
  
  
  - name: Install PyMySQL package
    apt:
      name: python3-pymysql
      state: present
    become: yes

  - name: MySQL database
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    become: yes
  
  - name: MySQL user
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      host: "%"
      priv: "{{ mysql_database }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock

