- name: Configure /etc/resolv.conf
  template:
    src: resolv.cnf.j2
    dest: /etc/resolv.conf

# - name: Disable systemd-resolved service
#   systemd:
#     name: systemd-resolved
#     enabled: no
#     state: stopped
#   become: yes