- name: Restart Mysql
  service:
    name: mysql
    state: restarted
  become: yes

- name: Restart mysql source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: 
    - stopslave
    - resetmaster
  when: inventory_hostname == mysql_host

- name: Restart mysql replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    master_host: "{{ mysql_host }}"
    master_user: "{{ mysql_replication_user }}"
    master_password: "{{ mysql_replication_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: 
    - stopslave
    - changemaster
    - resetslave
    - startslave
  when: inventory_hostname != mysql_host

- name: Restart Prometheus MySQL Exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
  become: yes

