- name: Install Bind9 package
  apt:
    name: bind9
    state: present
  tags: bind9

- name: Create configuration bind9 file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Create configuration bind9 for master and slave
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Create DNS Zone File
  template:
    src: dns_zone.j2
    dest: "/var/cache/bind/db.{{ startup_name }}"
  # when: inventory_hostname in groups ['dns_master']

- name: Ensure bind9 service is started and enabled
  service:
    name: bind9
    state: started
    enabled: yes

- name: Include Exporter Tasks
  include_tasks: exporters/main.yaml




