- name: Install Bind9 package
  apt:
    name: bind9
    state: present
  become: yes

- name: Create override.named.conf.options file
  template:
    src: bind_override.cnf.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Create DNS Zone File
  template:
    src: dns_zone.j2
    dest: "/var/lib/bind/db.{{ startup_name }}"
  become: yes

- name: Disable systemd-resolved service
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
  become: yes




