# - name: Create Linux user 'Juri'
#   user:
#     name: juri
#     state: present

# - name: Create Linux user 'Roman'
#   user:
#     name: roman
#     state: present

# - name: Ensure 'Juri' has authorized SSH key
#   authorized_key:
#     user: juri
#     key: |
#       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7TPxJ4rbrgO+cZzIzsU+PP6mk/3Njyb0dIFeCxuXWLhl2hNz5/4fzJUYxJV4ZYOE3aVLF14NrQec0uBvn4OKtCEXfBb+dNJqn8Zvqef529VexwAEha1qwCNKX4+mibYTCwX5sl2Vlu/qTQccc/ep2Te7Q561kVyl8WgpBnTrP+ogbXB5RDa1FxGx/Cwd7HN0p7RAob4efnGhpML8mrydnf0L8vvcJreAJLfjDwIdA1SYPBrSLKIrOhnncB0cEoFCbDD/LLNAG0igD3qgfu7FXEBvdFQQqj/9bxm3arg70dOb7yViqN+VHJ3sF7cnnRSuTSBuaLtSO9RJKfhaPLILDzdyl3HLnLbfmKZSqZN0nqczve8VRapLRlnKSpDDwadP4uiPuXDUAz0OwE7IYvbQUflZYiRrFZc9F6Pwp9W9PLZ+RoISY5YXWKsNbFIOTrhe2JfwoceCZgtxe5kZmlEq7I6Thd6EBPv7X/BlNZBpcgu1oaCBseQWsHkQoFcuZgLE=
#     state: present

# - name: Ensure 'Roman' has authorized SSH key
#   authorized_key:
#     user: roman
#     key: |
#       ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFligqCTgPl8lcKVsgHq9K9zEelCfTP+hcuG9tdhHgBoHwlZPilvTmi4veyORSGTuS9x8XwJuDAnAZsT75TFQVbOjp0XqqcpV/jF4ix6mS6kmdJzzruAaYSI6FWit4ZeRz8/XfNOmg2xaPn3A6hWAUAOhpeOiXtKcSZVOIitJOirjjYrK5Sq+cW8pFGjVWpweU46WwKYoPr1EyEN1PqUjDTOU4LvShEK1TF/kZOeRMysPf9lz1JQO6BKEr0oRWaROCMZwuTDlmh9i0LZEwje6e5ADxMyTHp9fgpCV9a4hDOE7EQdmePDtDO9PHjGQD3m060ydOiFbjSI98q0puzEKxpfzcyMEb/ztdiLWOBO5ANOMzADZ9f+D0S3bqHbSlq/pHXJ2aF2DfROKOrIg1ABFcgz4ugaGhQzYmxsKc2SXgzk/D7952k+FP5FxvW5FpX+xgkMGkt2XlLzjpvZO5eH/rHDppO1v+Pr876di5NbiXCC0GL3C80H2dl4QIrpeDtlFIO5spVtMqFBbUcXticNC9C6dXjOL5p5jhLq82tKHlc5Mnx0cyPRHeO8XCkA0MsipMOGy+tIiOPKaO/dDMT7kiYZKYvaNaUrmdB0MISydE8kTknHBVX9b/qOOysHglMJgmfIYP2YWXDVQFWq9hkWFVIS+yPiaEViphRKbTZMBbLQ==
#     state: present

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
    
########PROMETHEUS-EXPORTER##########

- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Start and Enable Node Exporter Service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install up-to-date CA certificates
  ansible.builtin.apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

#######RSYSLOG########

- name: Install rsyslog
  apt:
    name: rsyslog
    state: present

- name: Create a custom rsyslog configuration file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Modify a custom rsyslog configuration file
  template:
    src: rsyslog.confadvanced.j2
    dest: /etc/rsyslog.d/99-telegraf.conf
  notify: Restart rsyslog

#########BACKUP############

- name: Ensure the user 'backup' exists with a unique SSH key
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_file: "/home/backup/.ssh/id_rsa"

- name: Create known_hosts file for user backup
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
  become: yes

########BACKUP-CONFIG########

- name: Ensure /home/backup/restore directory exists
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    
- name: Ensure Duplicity is installed
  apt:
    name: duplicity
    state: present

# - name: Debug Grafana and Agama Ports
#   debug:
#     var: grafana_port

# - name: Debug Agama Port
#   debug:
#     var: agama_port




